services:
  solana-localnet:
    image: solanalabs/solana:v1.16.8
    container_name: solana-localnet
    restart: always
    command: >
      solana-test-validator
      --reset
      --log - # Logs to stdout
    ports:
      - "8899:8899" # RPC Port
      - "8900:8900" # Gossip Port
      - "8001:8001" # Entry Port
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.solana-localnet.rule=Host(`solana-localnet.yourdomain.com`)" # Replace with your domain
      - "traefik.http.routers.solana-localnet.tls=true"
      - "traefik.http.routers.solana-localnet.tls.certresolver=traefik-letsencrypt"
      - "traefik.http.services.solana-localnet.loadbalancer.server.port=8899"
    network_mode: traefik
